---
- name: devpi - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ devpi_configuration_directory }}"

- name: devpi - copy docker-compose.yml file
  template:
    src: devpi/docker-compose.yml.j2
    dest: "{{ devpi_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: devpi - pull images
  command: "docker-compose -f {{ devpi_docker_compose_directory }}/docker-compose.yml pull"
  register: result
  changed_when: ('Downloaded' in result.stdout)

- name: devpi - run service
  command: "docker-compose -f {{ devpi_docker_compose_directory }}/docker-compose.yml up -d --remove-orphans --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)
